<a href="https://colab.research.google.com/github/krissydolor/Linear-Algebra/blob/master/Assignmet_4_Baniquit_Dolor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Linear Algebra for ChE**

### **Laboratory 6 : Matrix Operations**

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

**Objectives**

At the end of this activity you will be able to:

1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## **Discussion**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

The numpy.transpose() method is a critical component of matrix multiplication. This function permutes or reserves the dimensions of an array and returns the resulting array. It reverses the order of the row and column items. This method returns a modified array of the original array.

$$
A=\begin{bmatrix} 1 & 2 & 5 \\ 5 & -1 & 0 \\ 0 & -3 & 3\end{bmatrix} \\
$$

$$
A^T =\begin{bmatrix} 1 & 5 & 0 \\ 2 & -1 & -3 \\ 5 & 0 & 3\end{bmatrix} \\
$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [2]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [3]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [4]:
AT2 = A.T

In [5]:
np.array_equiv(AT1, AT2)

True

In [6]:
B = np.array([
    [1,2,3,4],
    [1,0,2,1],
])
B.shape

(2, 4)

In [7]:
np.transpose(B).shape

(4, 2)

In [8]:
B.T.shape


(4, 2)

### **Dot Product / Inner Product**

Recalling the dot product from laboratory activity before, students will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$



$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

######In Python, one method of calculating the dot product would be to take the sum of list comprehension and conduct element-wise multiplication on the elements in the list. Alternatively, we can use the np. dot(), @, and np.matmul() functions to fulfill our objective on an easier method. A dot product of two arrays is the inner product of vectors if both a and b are 1-dimensional arrays, which means there is no complex conjugation.  In contrast, matrix multiplication is essential if a and b are 2-dimensional arrays; nonetheless, matmul or a @ b are equally preferable methods. Numpy's multiplier function can be used in place of arithmetic if either a or b is 0D (scalar). Multiplying (a, b) or a * b is preferable. 

In [9]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [10]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [11]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [12]:
X @ Y

array([[3, 4],
       [2, 2]])

In [13]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:



### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$C = \begin{bmatrix}0&1&2&4\\2&5&2&2\\0&1&5&6\end{bmatrix}, 
D = \begin{bmatrix}1&1&0\\3&3&0\\2&5&8\end{bmatrix}, 
O = \begin{bmatrix}2&0&4&5\\1&5&2&5\end{bmatrix}$$

So in this case $A$ has a shape of $(3,4)$, $B$ has a shape of $(3,3)$ and $C$ has a shape of $(2,2)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.







In [14]:
A = np.array([
    [2, 4],
    [5, -2],
    [0, 1]
])
B = np.array([
    [1,1],
    [3,3],
    [-1,-2]
])
C = np.array([
    [0,1,1],
    [1,1,2]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 2)
(3, 2)
(2, 3)


In [15]:
A @ C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [16]:
B @ C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A ⋅ B$ should hace a shape $(a,c)$.

In [17]:
A @ B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [18]:
X = np.array([
    [1,2,3,0]
])
Y = np.array([
    [1,0,4,-1]
])
print(X.shape)
print(Y.shape)

(1, 4)
(1, 4)


In [19]:
Y.T @ X

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$


In [20]:
A = np.array([
    [3,2,1],
    [4,5,1],
    [1,1,0]
])
B = np.array([
    [4,1,6],
    [4,1,9],
    [1,4,8]
])
C = np.array([
    [1,1,0],
    [0,1,1],
    [1,0,1]
])

In [21]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.array_equal(a_dot_z,z_mat)

True

In [25]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(a_dot_z,null)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


True

In [27]:
np.array_equiv(C.dot(B),A)

False

### **Determinant**
The matrix's determinant is the scalar value obtained for a given square matrix. Linear algebra is concerned with the determinant, which is calculated using the elements of a square matrix. It may be thought of as the scaling factor for a matrix transformation. Helpful in solving linear equations, computing the inverse of a matrix, and performing calculus operations.


In [ ]:
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

3.0000000000000004

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

## **Inverse**
The idea of the inverse matrix is a multidimensional refinement of the reciprocal of a number. The inverse matrix approach uses the inverse of a matrix to obtain the solution to linear equations. The inverse matrix is necessary because if a matrix rotates and scales a set of vectors, the inverse matrix undo the scalings and rotations to return the original vectors. On the other hand, using NumPy in the Python programming language can perform the concept of the inverse matrix. To calculate the inverse of a matrix, run the numpy.linalg.inv() that will serve as the function. 

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.


The inverse of a matrix is another matrix that produces the multiplicative identity when multiplied by the supplied matrix. $A^{-1}$ is the inverse of a matrix $A$, where $A \cdot\ A^{-1} = A^{-1} \cdot\ A = I$, where $I$ is the identity matrix.

In [30]:
N = np.array([
    [2, 2, 9],
    [4, -5, 2],
    [2, 0, 3]
])

np.array(N @ np.linalg.inv(N), dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
P = np.array([
    [2, 8, 2],
    [5, 2, 0],
    [2, 4, 6,]
              
])
Q = np.linalg.inv(P)
Q

array([[-0.06521739,  0.2173913 ,  0.02173913],
       [ 0.16304348, -0.04347826, -0.05434783],
       [-0.08695652, -0.04347826,  0.19565217]])

In [32]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [33]:
P @ Q

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 2.77555756e-17, -5.55111512e-17,  1.00000000e+00]])

### **Activity 1**

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [34]:
A = np.array([
    [3,2,1,5],
    [4,5,1,6],
    [1,1,0,6],
    [1,7,8,7]
])
B = np.array([
    [4,1,6,7],
    [4,1,9,3],
    [1,4,8,3],
    [1,4,8,3]
])
C = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,0,1,2],
    [3,4,5,6]
])

AB = np.matmul(A,B)
BA = np.matmul(B,A)
AC = np.matmul(A,C)
CA = np.matmul(C,A)
BC = np.matmul(B,C)
CB = np.matmul(C,B)
K = (AB)+(AC)
P = (BA)+(CA)

1. $A \cdot\ B \neq\ B \cdot\ A$

In [ ]:
print('Matrix AB:')
print(np.matmul(A,B))
print(f'Shape of Matrix AB:\t{np.matmul(A,B).shape}')

Matrix AB:
[[ 26  29  84  45]
 [ 43  37 125  64]
 [ 14  26  63  28]
 [ 47  68 189  73]]
Shape of Matrix AB:	(4, 4)


In [ ]:
print('Matrix BA:')
print(np.matmul(B,A))
print(f'Shape of Matrix BA:\t{np.matmul(B,A).shape}')

Matrix BA:
[[ 29  68  61 111]
 [ 28  43  29 101]
 [ 30  51  29  98]
 [ 30  51  29  98]]
Shape of Matrix BA:	(4, 4)


2. $A \cdot\ (B \cdot\ C) = (A \cdot\ B) \cdot\ C$

In [ ]:
print('Matrix A(BC):')
print(np.matmul(A,BC))
print(f'Shape of Matrix A(BC):\t{np.matmul(A,BC).shape}')

Matrix A(BC):
[[1062  406  590  774]
 [1545  564  833 1102]
 [ 795  296  427  558]
 [2307  794 1171 1548]]
Shape of Matrix A(BC):	(4, 4)


In [ ]:
print('Matrix (AB)C:')
print(np.matmul(AB,C))
print(f'Shape of Matrix (AB)C:\t{np.matmul(AB,C).shape}')

Matrix (AB)C:
[[1062  406  590  774]
 [1545  564  833 1102]
 [ 795  296  427  558]
 [2307  794 1171 1548]]
Shape of Matrix (AB)C:	(4, 4)


3. $A\cdot\ (B+C) = A\cdot\ B + A\cdot\ C$

In [ ]:
print('Matrix A(B+C):')
print(np.matmul(A,B+C))
print(f'Shape of Matrix A(B+C):\t{np.matmul(A,B+C).shape}')

Matrix A(B+C):
[[ 63  67 133 105]
 [ 99  99 203 158]
 [ 38  58 103  76]
 [176 140 284 191]]
Shape of Matrix A(B+C):	(4, 4)


In [ ]:
print('Matrix (AB)+(AC):')
print(K)
print(f'Shape of Matrix (AB)C:\t{K.shape}')

Matrix (AB)+(AC):
[[ 63  67 133 105]
 [ 99  99 203 158]
 [ 38  58 103  76]
 [176 140 284 191]]
Shape of Matrix (AB)C:	(4, 4)


3. $A\cdot\ (B+C) = A\cdot\ B + A\cdot\ C$

In [35]:
print('Matrix A(B+C):')
print(np.matmul(A,B+C))
print(f'Shape of Matrix A(B+C):\t{np.matmul(A,B+C).shape}')

Matrix A(B+C):
[[ 63  67 133 105]
 [ 99  99 203 158]
 [ 38  58 103  76]
 [176 140 284 191]]
Shape of Matrix A(B+C):	(4, 4)


In [36]:
print('Matrix (AB)+(AC):')
print(K)
print(f'Shape of Matrix (AB)C:\t{K.shape}')

Matrix (AB)+(AC):
[[ 63  67 133 105]
 [ 99  99 203 158]
 [ 38  58 103  76]
 [176 140 284 191]]
Shape of Matrix (AB)C:	(4, 4)


4. $(B+C)\cdot A = B\cdot A + C\cdot A$

In [37]:
print('Matrix B+C(A):')
print(np.matmul(B+C,A))
print(f'Shape of Matrix B+C(A):\t{np.matmul(B+C,A).shape}')

Matrix B+C(A):
[[ 47 111  96 174]
 [ 82 146 104 260]
 [ 60  84  54 163]
 [ 66 124  84 209]]
Shape of Matrix B+C(A):	(4, 4)


In [38]:
print('Matrix (BA)+(CA):')
print(P)
print(f'Shape of Matrix (BC)A:\t{P.shape}')

Matrix (BA)+(CA):
[[ 47 111  96 174]
 [ 82 146 104 260]
 [ 60  84  54 163]
 [ 66 124  84 209]]
Shape of Matrix (BC)A:	(4, 4)


 5. $A\cdot I = A$


In [39]:
A.dot(1)

array([[3, 2, 1, 5],
       [4, 5, 1, 6],
       [1, 1, 0, 6],
       [1, 7, 8, 7]])

 6. $A\cdot \emptyset = \emptyset$

In [40]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
A.dot(0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])